import { XIcon, ChevronLeftIcon, UserIcon, PillIcon, AlertCircleIcon, Building2Icon } from 'lucide-react';
import { useData } from '../context/DataContext';
interface PrescriptionDetailsProps {
    prescriptionId: string;
    onClose: () => void;
}
export function PrescriptionDetails({
    prescriptionId,
    onClose
}: PrescriptionDetailsProps) {
    const { prescriptions, processedData } = useData();

    // prescriptionId is "P{index+1}" as generated by PrescriptionsList
    const index = parseInt(prescriptionId.replace('P', ''), 10) - 1;
    const raw = prescriptions[index];

    if (!raw) {
        return <div className="h-full flex items-center justify-center">
            <div className="text-center">
                <p className="text-gray-500">Prescription not found.</p>
                <button onClick={onClose} className="mt-4 text-blue-600 hover:underline">Back to List</button>
            </div>
        </div>;
    }

    const riskScore = processedData.riskScores[raw.Doctor_ID] || 0;
    const status = riskScore >= 80 ? 'flagged' : 'normal';

    const alerts: { id: number; type: string; details: string; date: string }[] = [];
    if (riskScore >= 80) {
        alerts.push({
            id: 1,
            type: 'High Risk Prescriber',
            details: `Prescriber ${raw.Doctor_ID} has an elevated risk score of ${riskScore.toFixed(0)}`,
            date: raw.Prescription_Date
        });
    }
    if (['Opioid', 'Stimulant', 'Sedative'].includes(raw.Drug_Class)) {
        alerts.push({
            id: 2,
            type: 'Controlled Substance',
            details: `${raw.Drug_Name} is a controlled ${raw.Drug_Class.toLowerCase()} substance`,
            date: raw.Prescription_Date
        });
    }
    if (raw.Days_Supply > 0 && raw.Quantity / raw.Days_Supply > 3) {
        alerts.push({
            id: 3,
            type: 'High Daily Dosage',
            details: `${(raw.Quantity / raw.Days_Supply).toFixed(1)} units per day exceeds typical threshold`,
            date: raw.Prescription_Date
        });
    }

    const prescription = {
        id: prescriptionId,
        drug: raw.Drug_Name,
        drugClass: raw.Drug_Class,
        strength: raw.Strength,
        quantity: raw.Quantity,
        daysSupply: raw.Days_Supply,
        prescriber: {
            name: `Dr. ${raw.Doctor_ID}`,
            specialty: raw.Drug_Class,
            riskScore
        },
        patient: {
            id: raw.Patient_ID,
            riskScore: Math.min(riskScore * 0.85, 100)
        },
        pharmacy: {
            name: `Pharmacy ${raw.Pharmacy_ID}`,
            id: raw.Pharmacy_ID
        },
        date: raw.Prescription_Date,
        riskScore,
        status,
        alerts
    };
    return <div className="h-full flex flex-col">
        <div className="border-b border-gray-200 bg-white">
            <div className="px-6 py-4">
                <div className="flex items-center justify-between">
                    <button onClick={onClose} className="inline-flex items-center text-gray-600 hover:text-gray-800">
                        <ChevronLeftIcon size={20} className="mr-1" />
                        Back to List
                    </button>
                    <button onClick={onClose} className="p-2 rounded-md text-gray-400 hover:text-gray-500">
                        <XIcon size={20} />
                    </button>
                </div>
                <div className="mt-4 flex items-start justify-between">
                    <div className="flex items-center">
                        <div className="h-16 w-16 bg-gray-100 rounded-full flex items-center justify-center">
                            <PillIcon size={32} className="text-gray-500" />
                        </div>
                        <div className="ml-4">
                            <h1 className="text-2xl font-bold text-gray-900">
                                {prescription.drug}
                            </h1>
                            <p className="text-gray-600">
                                {prescription.strength} - {prescription.drugClass}
                            </p>
                        </div>
                    </div>
                    <div className="flex items-center space-x-4">
                        <span className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium ${prescription.riskScore >= 80 ? 'bg-red-100 text-red-800' : prescription.riskScore >= 60 ? 'bg-orange-100 text-orange-800' : 'bg-green-100 text-green-800'}`}>
                            Risk Score: {prescription.riskScore.toFixed(0)}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div className="flex-1 overflow-y-auto">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 p-6">
                <div className="lg:col-span-2 space-y-6">
                    <div className="bg-white rounded-lg shadow">
                        <div className="px-6 py-5 border-b border-gray-200">
                            <h2 className="text-lg font-medium text-gray-900">
                                Prescription Details
                            </h2>
                        </div>
                        <div className="p-6 grid grid-cols-2 gap-6">
                            <div>
                                <label className="text-sm font-medium text-gray-500">
                                    Quantity
                                </label>
                                <p className="mt-1 text-lg text-gray-900">
                                    {prescription.quantity} units
                                </p>
                            </div>
                            <div>
                                <label className="text-sm font-medium text-gray-500">
                                    Days Supply
                                </label>
                                <p className="mt-1 text-lg text-gray-900">
                                    {prescription.daysSupply} days
                                </p>
                            </div>
                            <div>
                                <label className="text-sm font-medium text-gray-500">
                                    Prescribed Date
                                </label>
                                <p className="mt-1 text-lg text-gray-900">
                                    {prescription.date}
                                </p>
                            </div>
                            <div>
                                <label className="text-sm font-medium text-gray-500">
                                    Status
                                </label>
                                <p className="mt-1 text-lg text-gray-900">
                                    {prescription.status.charAt(0).toUpperCase() + prescription.status.slice(1)}
                                </p>
                            </div>
                        </div>
                    </div>
                    {raw.Plan_Paid_Amount != null && (
                        <div className="bg-white rounded-lg shadow">
                            <div className="px-6 py-5 border-b border-gray-200">
                                <h2 className="text-lg font-medium text-gray-900">Pricing Details</h2>
                            </div>
                            <div className="p-6 grid grid-cols-2 gap-6">
                                {raw.AWP_Unit_Cost != null && <div>
                                    <label className="text-sm font-medium text-gray-500">AWP (per unit)</label>
                                    <p className="mt-1 text-lg text-gray-900">${raw.AWP_Unit_Cost.toFixed(2)}</p>
                                </div>}
                                {raw.Ingredient_Cost != null && <div>
                                    <label className="text-sm font-medium text-gray-500">Ingredient Cost</label>
                                    <p className="mt-1 text-lg text-gray-900">${raw.Ingredient_Cost.toFixed(2)}</p>
                                </div>}
                                <div>
                                    <label className="text-sm font-medium text-gray-500">Plan Paid</label>
                                    <p className="mt-1 text-lg text-gray-900">${(raw.Plan_Paid_Amount || 0).toFixed(2)}</p>
                                </div>
                                {raw.Patient_Paid_Amount != null && <div>
                                    <label className="text-sm font-medium text-gray-500">Patient Paid</label>
                                    <p className="mt-1 text-lg text-gray-900">${raw.Patient_Paid_Amount.toFixed(2)}</p>
                                </div>}
                                {raw.Reimbursement_Amount != null && <div>
                                    <label className="text-sm font-medium text-gray-500">Reimbursement</label>
                                    <p className="mt-1 text-lg text-gray-900">${raw.Reimbursement_Amount.toFixed(2)}</p>
                                </div>}
                                {raw.Reimbursement_Amount != null && raw.Plan_Paid_Amount != null && <div>
                                    <label className="text-sm font-medium text-gray-500">Spread</label>
                                    <p className={`mt-1 text-lg font-medium ${(raw.Plan_Paid_Amount - raw.Reimbursement_Amount) > 0 ? 'text-red-600' : 'text-green-600'}`}>
                                        ${(raw.Plan_Paid_Amount - raw.Reimbursement_Amount).toFixed(2)}
                                    </p>
                                </div>}
                                {raw.Contracted_Rate != null && <div>
                                    <label className="text-sm font-medium text-gray-500">Contracted Rate</label>
                                    <p className="mt-1 text-lg text-gray-900">${raw.Contracted_Rate.toFixed(2)}</p>
                                </div>}
                                {raw.Contracted_Rate != null && raw.Plan_Paid_Amount != null && <div>
                                    <label className="text-sm font-medium text-gray-500">Contract Compliance</label>
                                    <p className={`mt-1 text-lg font-medium ${Math.abs(raw.Plan_Paid_Amount - raw.Contracted_Rate) <= raw.Contracted_Rate * 0.02 ? 'text-green-600' : 'text-red-600'}`}>
                                        {Math.abs(raw.Plan_Paid_Amount - raw.Contracted_Rate) <= raw.Contracted_Rate * 0.02 ? 'Within tolerance' : 'Out of compliance'}
                                    </p>
                                </div>}
                            </div>
                        </div>
                    )}
                    <div className="bg-white rounded-lg shadow">
                        <div className="px-6 py-5 border-b border-gray-200">
                            <h2 className="text-lg font-medium text-gray-900">Alerts</h2>
                        </div>
                        <div className="divide-y divide-gray-200">
                            {prescription.alerts.map(alert => <div key={alert.id} className="px-6 py-4">
                                <div className="flex items-start">
                                    <AlertCircleIcon className="h-5 w-5 text-red-500 mt-0.5" />
                                    <div className="ml-3">
                                        <h3 className="text-sm font-medium text-gray-900">
                                            {alert.type}
                                        </h3>
                                        <p className="mt-1 text-sm text-gray-600">
                                            {alert.details}
                                        </p>
                                        <p className="mt-1 text-xs text-gray-500">
                                            {new Date(alert.date).toLocaleDateString()}
                                        </p>
                                    </div>
                                </div>
                            </div>)}
                        </div>
                    </div>
                </div>
                <div className="space-y-6">
                    <div className="bg-white rounded-lg shadow">
                        <div className="px-6 py-5 border-b border-gray-200">
                            <h2 className="text-lg font-medium text-gray-900">
                                Prescriber
                            </h2>
                        </div>
                        <div className="px-6 py-4">
                            <div className="flex items-center">
                                <UserIcon size={20} className="text-gray-400" />
                                <div className="ml-3">
                                    <p className="text-sm font-medium text-gray-900">
                                        {prescription.prescriber.name}
                                    </p>
                                    <p className="text-sm text-gray-500">
                                        {prescription.prescriber.specialty}
                                    </p>
                                </div>
                            </div>
                            <div className="mt-4">
                                <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${prescription.prescriber.riskScore >= 80 ? 'bg-red-100 text-red-800' : 'bg-orange-100 text-orange-800'}`}>
                                    Risk Score: {prescription.prescriber.riskScore.toFixed(0)}
                                </span>
                            </div>
                        </div>
                    </div>
                    <div className="bg-white rounded-lg shadow">
                        <div className="px-6 py-5 border-b border-gray-200">
                            <h2 className="text-lg font-medium text-gray-900">Pharmacy</h2>
                        </div>
                        <div className="px-6 py-4">
                            <div className="flex items-center">
                                <Building2Icon size={20} className="text-gray-400" />
                                <div className="ml-3">
                                    <p className="text-sm font-medium text-gray-900">
                                        {prescription.pharmacy.name}
                                    </p>
                                    <p className="text-sm text-gray-500 truncate" title={prescription.pharmacy.id}>
                                        {prescription.pharmacy.id}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="bg-white rounded-lg shadow">
                        <div className="px-6 py-5 border-b border-gray-200">
                            <h2 className="text-lg font-medium text-gray-900">
                                Patient Information
                            </h2>
                        </div>
                        <div className="px-6 py-4">
                            <div className="space-y-4">
                                <div>
                                    <label className="text-sm font-medium text-gray-500">
                                        Patient ID
                                    </label>
                                    <p className="mt-1 text-sm text-gray-900">
                                        {prescription.patient.id}
                                    </p>
                                </div>
                                <div>
                                    <label className="text-sm font-medium text-gray-500">
                                        Risk Score
                                    </label>
                                    <div className="mt-1">
                                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${prescription.patient.riskScore >= 80 ? 'bg-red-100 text-red-800' : 'bg-orange-100 text-orange-800'}`}>
                                            {prescription.patient.riskScore.toFixed(0)}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
}
